name: compas-fs2022
channels:
    - conda-forge

dependencies:
   - python=3.8
   - pip
   - git
   - compas=1.*
   - compas_fab>=0.22
   - igl>=2.2.1
   - compas_cgal>=0.4
   - compas_rrc
   - compas_slicer
